namespace XBRLToolkitID
{
    public class ImportantElementList{
 public static List<string> deiElements = new List<string>
      {
        "EntityName",
        "EntityCode",
        "EntityMainIndustry",
        "Sector",
        "SubSector",
        "Industry",
        "SubIndustry",
        "CurrentPeriodStartDate",
        "CurrentPeriodEndDate",
        "PeriodOfFinancialStatementsSubmissions"
    };

    public static List<string> financialElements = new List<string>
    {
        // =========================================================================
        // 1. NERACA UNIVERSAL & KUALITAS LABA (BERLAKU SEMUA SEKTOR)
        // =========================================================================
        "Assets",
        "CurrentAssets",
        "NonCurrentAssets",
        "Liabilities",
        "CurrentLiabilities",
        "NonCurrentLiabilities",
        "LiabilitiesAndEquity",
        "Equity",
        "EquityAttributableToEquityOwnersOfParentEntity",
        "NonControllingInterests",
        "AppropriatedRetainedEarnings",
        "UnappropriatedRetainedEarnings",
        "RetainedEarningsDeficit",
        "Cash",
        "CashAndCashEquivalents",
        "CashAndCashEquivalentsCashFlows",
        "RestrictedFunds",
        "CurrentRestrictedFunds",
        "NonCurrentRestrictedFunds",
        "TradeReceivablesGross",
        "TradeReceivablesNet",
        "TradeReceivablesThirdParties",
        "TradeReceivablesRelatedParties",
        "OtherReceivables",
        "OtherReceivablesThirdParties",
        "OtherReceivablesRelatedParties",
        "Inventories",
        "CurrentInventories",
        "NonCurrentInventories",
        "PropertyPlantAndEquipment",
        "IntangibleAssetsOtherThanGoodwill",
        "Goodwill",
        "InvestmentProperties",
        "RightOfUseAssets",
        "InvestmentsInAssociates",
        "InvestmentsInJointVentures",
        "TradePayables",
        "TradePayablesThirdParties",
        "TradePayablesRelatedParties",
        "OtherPayablesThirdParties",
        "OtherPayablesRelatedParties",
        "TaxesPayable",
        "CurrentAccruedExpenses",
        "AccruedExpenses",

        // =========================================================================
        // 2. LABA RUGI & ARUS KAS UNIVERSAL (SEMUA SEKTOR)
        // =========================================================================
        "SalesAndRevenue",
        "CostOfSalesAndRevenue",
        "GrossProfit",
        "SellingExpenses",
        "GeneralAndAdministrativeExpenses",
        "DepreciationAndAmortisationExpenses",
        "Depreciation",
        "Amortization",
        "ProfitFromOperation",
        "ProfitLossBeforeIncomeTax",
        "ProfitLoss",
        "ProfitLossAttributableToParentEntity",
        "ProfitLossAttributableToNonControllingInterests",
        "ComprehensiveIncome",
        "ComprehensiveIncomeAttributableToParentEntity",
        "ComprehensiveIncomeAttributableToNonControllingInterests",
        "NetCashFlowsReceivedFromUsedInOperatingActivities",
        "NetCashFlowsReceivedFromUsedInInvestingActivities",
        "NetCashFlowsReceivedFromUsedInFinancingActivities",
        "NetIncreaseDecreaseInCashAndCashEquivalents",
        "CashGeneratedFromUsedInOperations",
        "DividendsPaidFromOperatingActivities",
        "DividendsPaidFromFinancingActivities",
        "DividendsReceivedFromOperatingActivities",
        "DividendsReceivedFromInvestingActivities",

        // =========================================================================
        // 3. UTANG BERBUNGA & PEMBIAYAAN KORPORASI (TEV & SOLVABILITAS)
        // =========================================================================
        "Borrowings",
        "BorrowingsThirdParties",
        "BorrowingsRelatedParties",
        "ShortTermBankLoans",
        "ShortTermNonBankLoans",
        "LongTermBankLoans",
        "LongTermNon-BankFinancialInstitutionsLoan",
        "Bonds",
        "BondsPayable",
        "TotalBondsPayable",
        "Sukuk",
        "TotalSukuk",
        "FinanceLeaseLiabilities",
        "LongTermFinanceLeaseLiabilities",
        "SubordinatedLoans",
        "SubordinatedBonds",
        "CurrentMaturitiesOfBankLoans",
        "CurrentMaturitiesOfBondsPayable",
        "CurrentMaturitiesOfSukuk",
        "CurrentMaturitiesOfFinanceLeaseLiabilities",
        "CurrentMaturitiesOfNotesPayable",
        "CurrentMaturitiesOfMediumTermNotes",
        "CurrentMaturitiesOfSecuredLoans",
        "CurrentMaturitiesOfUnsecuredLoans",
        "CurrentMaturitiesOfSubordinatedLoans",
        "CurrentMaturitiesOfSubordinatedBonds",
        "CurrentMaturitiesOfOtherBorrowings",
        "LongTermNotesPayable",
        "LongTermMediumTermNotes",
        "LongTermSecuredLoans",
        "LongTermUnsecuredLoans",
        "LongTermSubordinatedLoans",
        "LongTermSubordinatedBonds",
        "LongTermSukuk",
        "LongTermOtherBorrowings",
        "InterestExpenses",
        "BorrowingsInterestExpense",
        "InterestAndFinanceCosts",
        "PaymentsOfBankLoans",
        "PaymentsOfBondsPayable",
        "PaymentsOfSukuk",
        "PaymentsOfFinanceLeaseLiabilities",
        "PaymentsOfInterestsFromBorrowings",
        "ProceedsFromBankLoans",
        "ProceedsFromBondsPayable",
        "ProceedsFromSukuk",
        "ProceedsFromBorrowings",

        // =========================================================================
        // 4. SEKTOR PROPERTI & REAL ESTAT
        // =========================================================================
        "RealEstateAssets",
        "RealEstateAssetsgross",
        "CurrentRealEstateAssets",
        "NonCurrentRealEstateAssets",
        "LandUnderDevelopmentInventory",
        "UndevelopedLand",
        "UndevelopedLandInventory",
        "BuildingAvailableforSale",
        "BuildingUnderConstruction",
        "CostOfLand",
        "ContractLiabilities",
        "CurrentContractLiabilities",
        "Non-CurrentContractLiabilities",
        "AdvancesFromCustomers",
        "AdvancesFromCustomersThirdParties",
        "AdvancesFromCustomersRelatedParties",
        "CurrentAdvancesFromCustomersThirdParties",
        "CurrentAdvancesFromCustomersRelatedParties",
        "LandAcquisitionLiabilities",
        "CurrentMaturitiesOfLandAcquisitionLiabilities",
        "LongTermLandAcquisitionLiabilities",
        "ProjectPayables",
        "AllowanceforImpairmentofRealEstateAssets",
        "PaymentsForAcquisitionOfLandForDevelopment",

        // =========================================================================
        // 5. SEKTOR PERBANKAN (KONVENSIONAL & SYARIAH)
        // =========================================================================
        "CurrentAccountsWithBankIndonesia",
        "CurrentAccountsWithOtherBanksThirdParties",
        "CurrentAccountsWithOtherBanksRelatedParties",
        "PlacementsWithBankIndonesiaAndOtherBanksThirdParties",
        "PlacementsWithBankIndonesiaAndOtherBanksRelatedParties",
        "LoansGross",
        "LoansNet",
        "LoansThirdParties",
        "LoansRelatedParties",
        "AllowanceLoans",
        "NonPerformingFinancingGross",
        "NonPerformingFinancingNet",
        "DueToCustomersThirdParties",
        "DueToCustomersRelatedParties",
        "CurrentAccountsThirdParties",
        "CurrentAccountsRelatedParties",
        "SavingsDeposits",
        "SavingsThirdParties",
        "SavingsRelatedParties",
        "TimeDepositsThirdParties",
        "TimeDepositsRelatedParties",
        "AcceptanceReceivablesThirdParties",
        "AcceptanceLiabilitiesThirdParties",
        "InterestIncome",
        "SubtotalInterestIncome",
        "SubtotalInterestExpense",
        // Komponen Khusus Syariah:
        "LiabilitiesTemporarySyirkahFundsAndEquity",
        "TemporarySyirkahFunds",
        "MudharabahCurrentAccount",
        "MudharabahSavingsDeposits",
        "MudharabahTimeDeposits",
        "MudharabahTemporarySyirkahFunds",
        "WadiahDemandDeposits",
        "WadiahSavingsDeposits",
        "WakalahDeposits",
        "ShariaReceivablesGross",
        "ShariaReceivablesNet",
        "MurabahahReceivablesThirdParties",
        "IstishnaReceivablesThirdParties",
        "IjarahReceivablesThirdParties",
        "MudharabahFinancingThirdParties",
        "MusyarakahFinancingThirdParties",
        "QardhFundsThirdParties",
        "AllowanceMurabahahReceivables",
        "AllowanceMusyarakahFinancing",
        "AllowanceMudharabahFinancing",
        "TotalInterestAndShariaIncome",
        "TotalInterestAndShariaExpense",

        // =========================================================================
        // 6. SEKTOR PEMBIAYAAN / MULTIFINANCE & SEKURITAS
        // =========================================================================
        "ConsumerFinancingReceivablesThirdParties",
        "AllowanceConsumerFinancingReceivables",
        "FinanceLeaseReceivables",
        "AllowanceLeaseInvestments",
        "FactoringReceivablesThirdParties",
        "AllowanceFactoring",
        "ConsumerFinancingPayables",
        "IncomeFromConsumerFinancing",
        "IncomeFromFinanceLease",
        "IncomeFromFactoring",
        "ReceivablesFromClearingAndSettlementGuaranteeInstitution",
        "PayablesToClearingAndSettlementGuaranteeInstitution",
        "ReceivablesFromBrokers",
        "IncomeFromBrokerageActivity",
        "IncomeFromUnderwritingActivitiesAndSellingFees",

        // =========================================================================
        // 7. SEKTOR ASURANSI (KONVENSIONAL & TABARRU/SYARIAH)
        // =========================================================================
        "InsuranceReceivablesThirdParties",
        "ReinsuranceReceivables",
        "ReinsuranceAssets",
        "InsuranceContractLiabilities",
        "InsuranceLiabilitiesForFuturePolicyBenefits",
        "InsuranceLiabilitiesOnUnearnedPremium",
        "InsuranceLiabilitiesOnEstimatedClaimsLiability",
        "InsurancePayables",
        "ReinsurancePayables",
        "ClaimPayables",
        "IncomeFromInsurancePremiums",
        "ClaimExpenses",
        "ReinsuranceClaims",
        "ReinsurancePremiums",
        "AccumulatedTabarrusFunds",
        "TabarrusFundsUnderwritingProfitLoss",
        "TabarrusFundsClaimPayments",

        // =========================================================================
        // 8. SEKTOR AGRIKULTUR, PERTAMBANGAN & INFRASTRUKTUR
        // =========================================================================
        "BiologicalAssets",
        "CurrentBiologicalAssets",
        "Non-CurrentBiologicalAssets",
        "LivestockInventories",
        "AllowanceforImpairmentofLiveStockInventories",
        "PlantationAssetsMature",
        "PlantationAssetsImmature",
        "PlasmaPlantations",
        "IndustrialTimberPlantationsMature",
        "IndustrialTimberPlantationsImmature",
        "ExplorationAndEvaluationAssets",
        "ExplorationExpenses",
        "OilAndGasAssets",
        "DeferredStrippingCosts",
        "CurrentDeferredStrippingCosts",
        "NonCurrentDeferredStrippingCosts",
        "TollRoadConcessionRights",
        "TollRoadMaintenanceExpenses",
        "TollCollectionExpenses",
        "ProvisionsForRestorationAndRehabilitation",
        "PaymentsForAcquisitionOfExplorationAndEvaluationAssets",
        "PaymentsForAcquisitionOfOilAndGasAssets",
        "PaymentsForAcquisitionOfMiningProperties",

        // =========================================================================
        // 9. FORENSIK CADANGAN, TRANSAKSI BERELASI & MODAL SAHAM
        // =========================================================================
        "AllowanceForImpairmentOfTradeReceivables",
        "AllowanceForImpairmentOfInventories",
        "AllowanceForImpairmentLossesOnEarningsAssets",
        "ImpairmentOfMovementOfAllowanceForImpairmentOfTradeReceivables",
        "IncreaseDecreaseforAllowanceForImpairmentOfInventory",
        "DueToRelatedParties",
        "DueToStockholders",
        "CurrentDueToRelatedParties",
        "CurrentDueToStockholders",
        "ReceivablesFromRelatedParties",
        "ReceivablesFromStockholders",
        "PaymentsOfReceivablesFromRelatedParties",
        "PaymentsOfReceivablesFromStockholders",
        "CommonStocks",
        "PreferredStocks",
        "TreasuryStocks",
        "AdditionalPaidInCapital",
        "ProceedsFromIssuanceOfCommonStocks",
        "ProceedsFromIssuanceOfNewStocks",
        "ProceedsFromSalesPurchasesOfTreasuryStocks",

        // =========================================================================
        // 10. CATATAN KAKI KRITIS (CALK TEXTBLOCK)
        // =========================================================================
        "DisclosureofNotesforRevenueTextBlock",
        "DisclosureofNotesforCostofGoodsSoldTextBlock",
        "DisclosureofNotesforTradeReceivablesTextBlock",
        "DisclosureofNotesforInventoriesTextBlock",
        "DisclosureofNotesforPropertyPlantandEquipmentTextBlock",
        "DisclosureofNotesforBorrowingsTextBlock",
        "DisclosureofNotesforShortTermBankLoansTextBlock",
        "DisclosureofNotesforLongTermBankLoansTextBlock",
        "DisclosureofNotesforBondsPayableTextBlock",
        "DisclosureofNotesforSukukTextBlock",
        "DisclosureofNotesforTradePayablesTextBlock",
        "TransactionsWithRelatedPartiesTextBlock",
        "SegmentReportingTextBlock",
        "ImpairmentOfNon-FinancialAssetsTextBlock"
    };
    };
   
}